---
- hosts: all
  tasks:

  - name: Create directory structure
    ansible.windows.win_file:
      path: C:\install\
      state: directory

  - name: copy adobe install file from share to remote host
    ansible.windows.win_copy:
      src: \\domsv4.intern.voso.ch\company\AcroRdrDC2200320322_en_US.exe
      dest: C:\install
      remote_src: true

  - name: Install Adobe Reader 
    ansible.windows.win_package:
      path: C:\install\AcroRdrDC2200320322_en_US.exe
      arguments: /S /D="C:\Program Files\Adobe"
      state: present
      log_path: C:\install\ansible_adobeinstall.log

