---
- hosts: all
  tasks:

  - name: Create directory structure
    ansible.windows.win_file:
      path: C:\install\
      state: directory

  - name: Download Notepad to specified path
    ansible.windows.win_get_url:
      url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.4.9/npp.8.4.9.Installer.x64.exe
      dest: C:\install


  - name: Install Notepad
    ansible.windows.win_package:
      path: C:\install\npp.8.4.9.Installer.x64.exe
      product_id: Notepad++
      arguments: '/S /D=C:\Program Files\Notepad\'
      state: present

  - name: Download 7zip to specified path
    win_get_url:
      url: https://www.7-zip.org/a/7z2201-x64.exe
      dest: C:\install

  - name: Install 7zip from local folder
    ansible.windows.win_package:
      path: C:\install\7z2201-x64.exe
      product_id: 7-Zip
      arguments: /S /D="C:\Program Files\7-Zipi"

