---
- hosts: all
  tasks:

  - name: Create directory structure
    ansible.windows.win_file:
      path: C:\install\Edge
      state: directory

  - name: copy Edge install file from share to remote host
    ansible.windows.win_copy:
      src: \\10.0.0.126\company\MicrosoftEdgeEnterpriseX64.msi
      dest: C:\install\Edge
      remote_src: true

  - name: Install Edge
    ansible.windows.win_powershell:
      script: |
        cmd /c start /wait msiexec /i C:\install\Edge\MicrosoftEdgeEnterpriseX64.msi /qn /norestart
