---
- hosts: all
  tasks:

  - name: Create directory structure
    ansible.windows.win_file:
      path: C:\install
      state: directory

  - name: copy ssms install file from share to remote host
    ansible.windows.win_copy:
      src: \\10.0.0.126\company\SSMS-Setup-ENU.exe
      dest: C:\install
      remote_src: true

  - name: Install SSMS on remote host
    ansible.windows.win_command:
      cmd: C:\install\SSMS-Setup-ENU.exe /quiet

