---
- hosts: all
  tasks:

  - name: Remove Adobe Reader with msiexec and product id
    ansible.windows.win_powershell:
        script: |
          Invoke-Command -ScriptBlock {'msiexec /x "{AC76BA86-7AD7-1033-7B44-AC0F074E4100}" /qn /norestart' | cmd}
