---
- hosts: all
  tasks:

  - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
    ansible.windows.win_updates:
      category_names: '*'
      state: searched
      log_path: C:\install\ansible_wu.txt

  - name: Store file into /tmp/fetched/host.example.com/tmp/somefile
    ansible.builtin.fetch:
      src: C:\install\ansible_wu.txt
      dest: /home/malon/WindowsServer/tmp/fetched


