---
- hosts: all

  vars:
    my_secret: Sauber88$

 


  tasks:
  - name: print the secure variable
    debug:
      var: my_secret
     


  - name: copy a file from a fileshare with custom credentials
    ansible.windows.win_copy:
      src: \\10.0.0.126\company\Thunder.msi
      dest: C:\install
      remote_src: true
    vars:
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: malon
      ansible_become_password: "{{ my_secret }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only

